# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loginUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 280)
        MainWindow.setMinimumSize(QtCore.QSize(400, 280))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(20, 10, 361, 241))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.layoutWidget = QtWidgets.QWidget(self.frame)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 10, 321, 131))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.txtUser = QtWidgets.QLineEdit(self.layoutWidget)
        self.txtUser.setClearButtonEnabled(True)
        self.txtUser.setObjectName("txtUser")
        self.verticalLayout.addWidget(self.txtUser)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.txtPass = QtWidgets.QLineEdit(self.layoutWidget)
        self.txtPass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txtPass.setClearButtonEnabled(True)
        self.txtPass.setObjectName("txtPass")
        self.verticalLayout.addWidget(self.txtPass)
        self.btnEntrar = QtWidgets.QPushButton(self.frame)
        self.btnEntrar.setGeometry(QtCore.QRect(20, 190, 321, 34))
        self.btnEntrar.setStyleSheet("background-color: rgb(120, 0, 180);")
        self.btnEntrar.setObjectName("btnEntrar")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Tela Login - Mehsys"))
        self.label.setToolTip(_translate("MainWindow", "Nome de usuário"))
        self.label.setStatusTip(_translate("MainWindow", "Nome de usuário"))
        self.label.setText(_translate("MainWindow", "Usuário:"))
        self.txtUser.setToolTip(_translate("MainWindow", "Nome de usuário"))
        self.txtUser.setStatusTip(_translate("MainWindow", "Nome de usuário"))
        self.txtUser.setPlaceholderText(_translate("MainWindow", "Nome de usuário"))
        self.label_2.setToolTip(_translate("MainWindow", "Senha do usuário"))
        self.label_2.setStatusTip(_translate("MainWindow", "Senha do usuário"))
        self.label_2.setText(_translate("MainWindow", "Senha:"))
        self.txtPass.setToolTip(_translate("MainWindow", "Senha do usuário"))
        self.txtPass.setStatusTip(_translate("MainWindow", "Senha do usuário"))
        self.txtPass.setPlaceholderText(_translate("MainWindow", "Senha do usuário"))
        self.btnEntrar.setToolTip(_translate("MainWindow", "Entrar"))
        self.btnEntrar.setStatusTip(_translate("MainWindow", "Entrar"))
        self.btnEntrar.setText(_translate("MainWindow", "Entrar"))
