# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'principalUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(750, 600)
        MainWindow.setMinimumSize(QtCore.QSize(750, 600))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/logo/img/logo_gra.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_10.setContentsMargins(6, -1, -1, -1)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setStyleSheet("QPushButton{\n"
"    border-radius: 5px;\n"
"    border: 1px solid rgb(100, 100, 100);\n"
"    height: 30px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(0, 50, 200);\n"
"}")
        self.tabWidget.setObjectName("tabWidget")
        self.tabHor = QtWidgets.QWidget()
        self.tabHor.setObjectName("tabHor")
        self.line = QtWidgets.QFrame(self.tabHor)
        self.line.setGeometry(QtCore.QRect(20, 198, 691, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.table_hor = QtWidgets.QTableWidget(self.tabHor)
        self.table_hor.setGeometry(QtCore.QRect(20, 265, 691, 225))
        self.table_hor.setObjectName("table_hor")
        self.table_hor.setColumnCount(6)
        self.table_hor.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_hor.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_hor.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_hor.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_hor.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_hor.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_hor.setHorizontalHeaderItem(5, item)
        self.layoutWidget = QtWidgets.QWidget(self.tabHor)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 0, 691, 141))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.txtPesCli_hor = QtWidgets.QLineEdit(self.layoutWidget)
        self.txtPesCli_hor.setClearButtonEnabled(True)
        self.txtPesCli_hor.setObjectName("txtPesCli_hor")
        self.verticalLayout.addWidget(self.txtPesCli_hor)
        self.cbbSer_hor = QtWidgets.QComboBox(self.layoutWidget)
        self.cbbSer_hor.setObjectName("cbbSer_hor")
        self.verticalLayout.addWidget(self.cbbSer_hor)
        self.cbbPro_hor = QtWidgets.QComboBox(self.layoutWidget)
        self.cbbPro_hor.setObjectName("cbbPro_hor")
        self.verticalLayout.addWidget(self.cbbPro_hor)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.txtId_hor = QtWidgets.QLineEdit(self.layoutWidget)
        self.txtId_hor.setEnabled(False)
        self.txtId_hor.setObjectName("txtId_hor")
        self.verticalLayout_2.addWidget(self.txtId_hor)
        self.dat_hor = QtWidgets.QDateEdit(self.layoutWidget)
        self.dat_hor.setObjectName("dat_hor")
        self.verticalLayout_2.addWidget(self.dat_hor)
        self.cbbHor_hor = QtWidgets.QComboBox(self.layoutWidget)
        self.cbbHor_hor.setObjectName("cbbHor_hor")
        self.verticalLayout_2.addWidget(self.cbbHor_hor)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.layoutWidget1 = QtWidgets.QWidget(self.tabHor)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 143, 691, 51))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnAge_hor = QtWidgets.QPushButton(self.layoutWidget1)
        self.btnAge_hor.setStyleSheet("QPushButton{\n"
"    border-radius: 5px;\n"
"    border: 1px solid #850085;\n"
"    background-color: #850085;\n"
"    height: 30px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(0, 50, 200);\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/img/plus-border.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAge_hor.setIcon(icon1)
        self.btnAge_hor.setObjectName("btnAge_hor")
        self.horizontalLayout_2.addWidget(self.btnAge_hor)
        self.btnAtu_hor = QtWidgets.QPushButton(self.layoutWidget1)
        self.btnAtu_hor.setEnabled(False)
        self.btnAtu_hor.setStyleSheet("QPushButton{\n"
"    border-radius: 5px;\n"
"    border: 1px solid rgb(100, 100, 100);\n"
"    height: 30px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(0, 50, 200);\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/img/refresh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAtu_hor.setIcon(icon2)
        self.btnAtu_hor.setObjectName("btnAtu_hor")
        self.horizontalLayout_2.addWidget(self.btnAtu_hor)
        self.btnExc_hor = QtWidgets.QPushButton(self.layoutWidget1)
        self.btnExc_hor.setEnabled(False)
        self.btnExc_hor.setStyleSheet("QPushButton{\n"
"    border-radius: 5px;\n"
"    border: 1px solid rgb(100, 100, 100);\n"
"    height: 30px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(0, 50, 200);\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/img/edit-delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnExc_hor.setIcon(icon3)
        self.btnExc_hor.setObjectName("btnExc_hor")
        self.horizontalLayout_2.addWidget(self.btnExc_hor)
        self.btnImp_hor = QtWidgets.QPushButton(self.layoutWidget1)
        self.btnImp_hor.setEnabled(False)
        self.btnImp_hor.setStyleSheet("QPushButton{\n"
"    border-radius: 5px;\n"
"    border: 1px solid rgb(100, 100, 100);\n"
"    height: 30px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(0, 50, 200);\n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/img/print.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnImp_hor.setIcon(icon4)
        self.btnImp_hor.setObjectName("btnImp_hor")
        self.horizontalLayout_2.addWidget(self.btnImp_hor)
        self.btnLim_hor = QtWidgets.QPushButton(self.layoutWidget1)
        self.btnLim_hor.setStyleSheet("QPushButton{\n"
"    border-radius: 5px;\n"
"    border: 1px solid #850085;\n"
"    height: 30px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(0, 50, 200);\n"
"}")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/img/limpar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnLim_hor.setIcon(icon5)
        self.btnLim_hor.setObjectName("btnLim_hor")
        self.horizontalLayout_2.addWidget(self.btnLim_hor)
        self.layoutWidget2 = QtWidgets.QWidget(self.tabHor)
        self.layoutWidget2.setGeometry(QtCore.QRect(20, 223, 691, 41))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.txtPesNom_hor = QtWidgets.QLineEdit(self.layoutWidget2)
        self.txtPesNom_hor.setClearButtonEnabled(True)
        self.txtPesNom_hor.setObjectName("txtPesNom_hor")
        self.horizontalLayout_3.addWidget(self.txtPesNom_hor)
        self.btnPesNom_hor = QtWidgets.QPushButton(self.layoutWidget2)
        self.btnPesNom_hor.setStyleSheet("QPushButton{\n"
"    border-radius: 5px;\n"
"    border: 1px solid #850085;\n"
"    height: 30px;\n"
"    padding-right: 10px;\n"
"    padding-left: 10px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(0, 50, 200);\n"
"}")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/img/pesquisar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnPesNom_hor.setIcon(icon6)
        self.btnPesNom_hor.setObjectName("btnPesNom_hor")
        self.horizontalLayout_3.addWidget(self.btnPesNom_hor)
        self.txtPesDat_hor = QtWidgets.QLineEdit(self.layoutWidget2)
        self.txtPesDat_hor.setClearButtonEnabled(True)
        self.txtPesDat_hor.setObjectName("txtPesDat_hor")
        self.horizontalLayout_3.addWidget(self.txtPesDat_hor)
        self.btnPesDat_hor = QtWidgets.QPushButton(self.layoutWidget2)
        self.btnPesDat_hor.setStyleSheet("QPushButton{\n"
"    border-radius: 5px;\n"
"    border: 1px solid #850085;\n"
"    height: 30px;\n"
"    padding-right: 10px;\n"
"    padding-left: 10px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(0, 50, 200);\n"
"}")
        self.btnPesDat_hor.setIcon(icon6)
        self.btnPesDat_hor.setObjectName("btnPesDat_hor")
        self.horizontalLayout_3.addWidget(self.btnPesDat_hor)
        self.listPesCli_hor = QtWidgets.QListWidget(self.tabHor)
        self.listPesCli_hor.setGeometry(QtCore.QRect(21, 38, 341, 90))
        self.listPesCli_hor.setObjectName("listPesCli_hor")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/img/agendamento.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tabHor, icon7, "")
        self.tabCli = QtWidgets.QWidget()
        self.tabCli.setObjectName("tabCli")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tabCli)
        self.verticalLayout_7.setContentsMargins(20, 12, 20, 12)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(0, 6, -1, 6)
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(12)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.txtNom_cli = QtWidgets.QLineEdit(self.tabCli)
        self.txtNom_cli.setClearButtonEnabled(True)
        self.txtNom_cli.setObjectName("txtNom_cli")
        self.verticalLayout_3.addWidget(self.txtNom_cli)
        self.cbcSex_cli = QtWidgets.QComboBox(self.tabCli)
        self.cbcSex_cli.setObjectName("cbcSex_cli")
        self.cbcSex_cli.addItem("")
        self.cbcSex_cli.addItem("")
        self.cbcSex_cli.addItem("")
        self.verticalLayout_3.addWidget(self.cbcSex_cli)
        self.txtCpf_cli = QtWidgets.QLineEdit(self.tabCli)
        self.txtCpf_cli.setClearButtonEnabled(True)
        self.txtCpf_cli.setObjectName("txtCpf_cli")
        self.verticalLayout_3.addWidget(self.txtCpf_cli)
        self.horizontalLayout_6.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(12)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.txtId_cli = QtWidgets.QLineEdit(self.tabCli)
        self.txtId_cli.setEnabled(False)
        self.txtId_cli.setObjectName("txtId_cli")
        self.verticalLayout_4.addWidget(self.txtId_cli)
        self.txtEnd_cli = QtWidgets.QLineEdit(self.tabCli)
        self.txtEnd_cli.setObjectName("txtEnd_cli")
        self.verticalLayout_4.addWidget(self.txtEnd_cli)
        self.txtFon_cli = QtWidgets.QLineEdit(self.tabCli)
        self.txtFon_cli.setObjectName("txtFon_cli")
        self.verticalLayout_4.addWidget(self.txtFon_cli)
        self.horizontalLayout_6.addLayout(self.verticalLayout_4)
        self.verticalLayout_7.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(0, 12, 0, 15)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.btnSal_cli = QtWidgets.QPushButton(self.tabCli)
        self.btnSal_cli.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnSal_cli.setStyleSheet("QPushButton{\n"
"    border-radius: 5px;\n"
"    border: 1px solid rgb(0, 140, 0);\n"
"    background-color: rgb(0, 150, 0);\n"
"height: 30px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(0, 50, 200);\n"
"}")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/img/salvar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSal_cli.setIcon(icon8)
        self.btnSal_cli.setObjectName("btnSal_cli")
        self.horizontalLayout_5.addWidget(self.btnSal_cli)
        self.btnAtu_cli = QtWidgets.QPushButton(self.tabCli)
        self.btnAtu_cli.setEnabled(False)
        self.btnAtu_cli.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnAtu_cli.setStyleSheet("QPushButton{\n"
"    border-radius: 5px;\n"
"    border: 1px solid rgb(100, 100, 100);\n"
"    height: 30px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(0, 50, 200);\n"
"}")
        self.btnAtu_cli.setIcon(icon2)
        self.btnAtu_cli.setObjectName("btnAtu_cli")
        self.horizontalLayout_5.addWidget(self.btnAtu_cli)
        self.btnExc_cli = QtWidgets.QPushButton(self.tabCli)
        self.btnExc_cli.setEnabled(False)
        self.btnExc_cli.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnExc_cli.setStyleSheet("QPushButton{\n"
"    border-radius: 5px;\n"
"    border: 1px solid rgb(100, 100, 100);\n"
"    height: 30px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(0, 50, 200);\n"
"}")
        self.btnExc_cli.setIcon(icon3)
        self.btnExc_cli.setObjectName("btnExc_cli")
        self.horizontalLayout_5.addWidget(self.btnExc_cli)
        self.btnLim_cli = QtWidgets.QPushButton(self.tabCli)
        self.btnLim_cli.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnLim_cli.setStyleSheet("QPushButton{\n"
"    border-radius: 5px;\n"
"    border: 1px solid rgb(0, 140, 0);\n"
"    height: 30px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(0, 50, 200);\n"
"}")
        self.btnLim_cli.setIcon(icon5)
        self.btnLim_cli.setObjectName("btnLim_cli")
        self.horizontalLayout_5.addWidget(self.btnLim_cli)
        self.verticalLayout_7.addLayout(self.horizontalLayout_5)
        self.line_2 = QtWidgets.QFrame(self.tabCli)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_7.addWidget(self.line_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(100, 12, 100, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.txtPesNom_cli = QtWidgets.QLineEdit(self.tabCli)
        self.txtPesNom_cli.setClearButtonEnabled(True)
        self.txtPesNom_cli.setObjectName("txtPesNom_cli")
        self.horizontalLayout_4.addWidget(self.txtPesNom_cli)
        self.btnPesNom_cli = QtWidgets.QPushButton(self.tabCli)
        self.btnPesNom_cli.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnPesNom_cli.setStyleSheet("QPushButton{\n"
"    border-radius: 5px;\n"
"    border: 1px solid rgb(0, 140, 0);\n"
"    padding-left: 10px;\n"
"    padding-right:10px;\n"
"    height: 30px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(0, 50, 200);\n"
"}")
        self.btnPesNom_cli.setIcon(icon6)
        self.btnPesNom_cli.setObjectName("btnPesNom_cli")
        self.horizontalLayout_4.addWidget(self.btnPesNom_cli)
        self.verticalLayout_7.addLayout(self.horizontalLayout_4)
        self.table_cli = QtWidgets.QTableWidget(self.tabCli)
        self.table_cli.setObjectName("table_cli")
        self.table_cli.setColumnCount(6)
        self.table_cli.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_cli.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_cli.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_cli.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_cli.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_cli.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_cli.setHorizontalHeaderItem(5, item)
        self.verticalLayout_7.addWidget(self.table_cli)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/img/cli_ico.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tabCli, icon9, "")
        self.tabSer = QtWidgets.QWidget()
        self.tabSer.setObjectName("tabSer")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.tabSer)
        self.verticalLayout_8.setContentsMargins(20, 12, 20, 12)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setContentsMargins(-1, 6, -1, 6)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSpacing(12)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.txtNom_ser = QtWidgets.QLineEdit(self.tabSer)
        self.txtNom_ser.setClearButtonEnabled(True)
        self.txtNom_ser.setObjectName("txtNom_ser")
        self.verticalLayout_5.addWidget(self.txtNom_ser)
        self.cbbPro_ser = QtWidgets.QComboBox(self.tabSer)
        self.cbbPro_ser.setObjectName("cbbPro_ser")
        self.verticalLayout_5.addWidget(self.cbbPro_ser)
        self.txtSer_ser = QtWidgets.QLineEdit(self.tabSer)
        self.txtSer_ser.setClearButtonEnabled(True)
        self.txtSer_ser.setObjectName("txtSer_ser")
        self.verticalLayout_5.addWidget(self.txtSer_ser)
        self.horizontalLayout_9.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setSpacing(12)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.txtId_ser = QtWidgets.QLineEdit(self.tabSer)
        self.txtId_ser.setEnabled(False)
        self.txtId_ser.setObjectName("txtId_ser")
        self.verticalLayout_6.addWidget(self.txtId_ser)
        self.horHor_ser = QtWidgets.QLineEdit(self.tabSer)
        self.horHor_ser.setObjectName("horHor_ser")
        self.verticalLayout_6.addWidget(self.horHor_ser)
        spacerItem = QtWidgets.QSpacerItem(14, 35, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_6.addItem(spacerItem)
        self.horizontalLayout_9.addLayout(self.verticalLayout_6)
        self.verticalLayout_8.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(-1, 12, -1, 15)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.pushButton_17 = QtWidgets.QPushButton(self.tabSer)
        self.pushButton_17.setStyleSheet("QPushButton{\n"
"    border-radius: 5px;\n"
"    border: 1px solid rgb(0, 0, 140);\n"
"    background-color: rgb(0, 0, 150);\n"
"    height: 30px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(0, 50, 200);\n"
"}")
        self.pushButton_17.setIcon(icon8)
        self.pushButton_17.setObjectName("pushButton_17")
        self.horizontalLayout_8.addWidget(self.pushButton_17)
        self.pushButton_18 = QtWidgets.QPushButton(self.tabSer)
        self.pushButton_18.setEnabled(False)
        self.pushButton_18.setStyleSheet("QPushButton{\n"
"    border-radius: 5px;\n"
"    border: 1px solid rgb(100, 100, 100);\n"
"    height: 30px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(0, 50, 200);\n"
"}")
        self.pushButton_18.setIcon(icon2)
        self.pushButton_18.setObjectName("pushButton_18")
        self.horizontalLayout_8.addWidget(self.pushButton_18)
        self.pushButton_19 = QtWidgets.QPushButton(self.tabSer)
        self.pushButton_19.setEnabled(False)
        self.pushButton_19.setStyleSheet("QPushButton{\n"
"    border-radius: 5px;\n"
"    border: 1px solid rgb(100, 100, 100);\n"
"    height: 30px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(0, 50, 200);\n"
"}")
        self.pushButton_19.setIcon(icon3)
        self.pushButton_19.setObjectName("pushButton_19")
        self.horizontalLayout_8.addWidget(self.pushButton_19)
        self.pushButton_21 = QtWidgets.QPushButton(self.tabSer)
        self.pushButton_21.setStyleSheet("QPushButton{\n"
"    border-radius: 5px;\n"
"    border: 1px solid rgb(0, 0, 150);\n"
"    height: 30px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(0, 50, 200);\n"
"}")
        self.pushButton_21.setIcon(icon5)
        self.pushButton_21.setObjectName("pushButton_21")
        self.horizontalLayout_8.addWidget(self.pushButton_21)
        self.verticalLayout_8.addLayout(self.horizontalLayout_8)
        self.line_3 = QtWidgets.QFrame(self.tabSer)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_8.addWidget(self.line_3)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(100, 12, 100, -1)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.tabSer)
        self.lineEdit_9.setClearButtonEnabled(True)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.horizontalLayout_7.addWidget(self.lineEdit_9)
        self.pushButton_15 = QtWidgets.QPushButton(self.tabSer)
        self.pushButton_15.setStyleSheet("QPushButton{\n"
"    border-radius: 5px;\n"
"    border: 1px solid rgb(0, 0, 150);\n"
"    padding-left: 10px;\n"
"    padding-right:10px;\n"
"    height: 30px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(0, 50, 200);\n"
"}")
        self.pushButton_15.setIcon(icon6)
        self.pushButton_15.setObjectName("pushButton_15")
        self.horizontalLayout_7.addWidget(self.pushButton_15)
        self.verticalLayout_8.addLayout(self.horizontalLayout_7)
        self.table_ser = QtWidgets.QTableWidget(self.tabSer)
        self.table_ser.setObjectName("table_ser")
        self.table_ser.setColumnCount(5)
        self.table_ser.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_ser.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_ser.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_ser.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_ser.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_ser.setHorizontalHeaderItem(4, item)
        self.verticalLayout_8.addWidget(self.table_ser)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icons/img/ser_ico.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tabSer, icon10, "")
        self.horizontalLayout_10.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 750, 28))
        self.menubar.setObjectName("menubar")
        self.menuAtendimentos = QtWidgets.QMenu(self.menubar)
        self.menuAtendimentos.setObjectName("menuAtendimentos")
        self.menuClientes = QtWidgets.QMenu(self.menubar)
        self.menuClientes.setObjectName("menuClientes")
        self.menuHor_rios = QtWidgets.QMenu(self.menubar)
        self.menuHor_rios.setObjectName("menuHor_rios")
        self.menuServi_os = QtWidgets.QMenu(self.menubar)
        self.menuServi_os.setObjectName("menuServi_os")
        self.menuSair = QtWidgets.QMenu(self.menubar)
        self.menuSair.setObjectName("menuSair")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionClientes = QtWidgets.QAction(MainWindow)
        self.actionClientes.setIcon(icon9)
        self.actionClientes.setObjectName("actionClientes")
        self.actionHor_rios = QtWidgets.QAction(MainWindow)
        self.actionHor_rios.setIcon(icon7)
        self.actionHor_rios.setObjectName("actionHor_rios")
        self.actionServi_os = QtWidgets.QAction(MainWindow)
        self.actionServi_os.setIcon(icon10)
        self.actionServi_os.setObjectName("actionServi_os")
        self.actionUsu_rios = QtWidgets.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/icons/img/usuario.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionUsu_rios.setIcon(icon11)
        self.actionUsu_rios.setObjectName("actionUsu_rios")
        self.actionClientes_2 = QtWidgets.QAction(MainWindow)
        self.actionClientes_2.setIcon(icon4)
        self.actionClientes_2.setObjectName("actionClientes_2")
        self.actionHor_rios_2 = QtWidgets.QAction(MainWindow)
        self.actionHor_rios_2.setIcon(icon4)
        self.actionHor_rios_2.setObjectName("actionHor_rios_2")
        self.actionServi_os_2 = QtWidgets.QAction(MainWindow)
        self.actionServi_os_2.setIcon(icon4)
        self.actionServi_os_2.setObjectName("actionServi_os_2")
        self.actionAjuda = QtWidgets.QAction(MainWindow)
        self.actionAjuda.setObjectName("actionAjuda")
        self.actionAddHor = QtWidgets.QAction(MainWindow)
        self.actionAddHor.setIcon(icon1)
        self.actionAddHor.setObjectName("actionAddHor")
        self.actionSair_2 = QtWidgets.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/icons/img/exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSair_2.setIcon(icon12)
        self.actionSair_2.setObjectName("actionSair_2")
        self.actionSobre = QtWidgets.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/icons/img/inf2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSobre.setIcon(icon13)
        self.actionSobre.setObjectName("actionSobre")
        self.menuAtendimentos.addAction(self.actionHor_rios)
        self.menuAtendimentos.addAction(self.actionClientes)
        self.menuAtendimentos.addAction(self.actionServi_os)
        self.menuClientes.addAction(self.actionUsu_rios)
        self.menuHor_rios.addAction(self.actionHor_rios_2)
        self.menuHor_rios.addAction(self.actionClientes_2)
        self.menuHor_rios.addAction(self.actionServi_os_2)
        self.menuServi_os.addAction(self.actionAddHor)
        self.menuServi_os.addAction(self.actionSobre)
        self.menuSair.addAction(self.actionSair_2)
        self.menubar.addAction(self.menuAtendimentos.menuAction())
        self.menubar.addAction(self.menuClientes.menuAction())
        self.menubar.addAction(self.menuHor_rios.menuAction())
        self.menubar.addAction(self.menuServi_os.menuAction())
        self.menubar.addAction(self.menuSair.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Tela Principal - Mehsys"))
        self.table_hor.setStatusTip(_translate("MainWindow", "Selecione algum agendamento para atualizar ou deletar"))
        item = self.table_hor.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Id"))
        item = self.table_hor.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Cliente"))
        item = self.table_hor.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Serviço"))
        item = self.table_hor.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Data"))
        item = self.table_hor.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Horário"))
        item = self.table_hor.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Profissional"))
        self.txtPesCli_hor.setStatusTip(_translate("MainWindow", "Digite qualquer coisa para pesquisar um cliente"))
        self.txtPesCli_hor.setPlaceholderText(_translate("MainWindow", "Pesquisar cliente"))
        self.cbbSer_hor.setStatusTip(_translate("MainWindow", "Selecione um serviço"))
        self.cbbSer_hor.setPlaceholderText(_translate("MainWindow", "Selecionar serviço"))
        self.cbbPro_hor.setStatusTip(_translate("MainWindow", "Selecione um profissional"))
        self.cbbPro_hor.setPlaceholderText(_translate("MainWindow", "Selecionar Profissional"))
        self.txtId_hor.setStatusTip(_translate("MainWindow", "Código do agendamento"))
        self.txtId_hor.setPlaceholderText(_translate("MainWindow", "Id"))
        self.dat_hor.setStatusTip(_translate("MainWindow", "Digite data para o agendamento"))
        self.cbbHor_hor.setStatusTip(_translate("MainWindow", "Selecione horário disponível(se não aparecer nada clique fora ou no botão \'Agendar\')"))
        self.cbbHor_hor.setPlaceholderText(_translate("MainWindow", "Selecionar horário"))
        self.btnAge_hor.setStatusTip(_translate("MainWindow", "Criar novo agendamento"))
        self.btnAge_hor.setText(_translate("MainWindow", "Agendar"))
        self.btnAtu_hor.setStatusTip(_translate("MainWindow", "Atualizar agendameto"))
        self.btnAtu_hor.setText(_translate("MainWindow", "Atualizar"))
        self.btnExc_hor.setStatusTip(_translate("MainWindow", "Deletar agendamento"))
        self.btnExc_hor.setText(_translate("MainWindow", "Excluir"))
        self.btnImp_hor.setStatusTip(_translate("MainWindow", "Imprimir comprovante"))
        self.btnImp_hor.setText(_translate("MainWindow", "Imprimir"))
        self.btnLim_hor.setStatusTip(_translate("MainWindow", "Limpar campos para poder realizar novo agendamento"))
        self.btnLim_hor.setText(_translate("MainWindow", "Limpar"))
        self.txtPesNom_hor.setStatusTip(_translate("MainWindow", "Pesquisar agendamentos por nome do cliente"))
        self.txtPesNom_hor.setPlaceholderText(_translate("MainWindow", "Nome cliente"))
        self.btnPesNom_hor.setStatusTip(_translate("MainWindow", "Pesquisar agendamentos por nome de cliente"))
        self.btnPesNom_hor.setText(_translate("MainWindow", "Pesquisar"))
        self.txtPesDat_hor.setStatusTip(_translate("MainWindow", "pesquisar agendamento por data"))
        self.txtPesDat_hor.setPlaceholderText(_translate("MainWindow", "Data agendamento"))
        self.btnPesDat_hor.setStatusTip(_translate("MainWindow", "Pesquisar agendamento por data"))
        self.btnPesDat_hor.setText(_translate("MainWindow", "Pesquisar"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabHor), _translate("MainWindow", "Horários"))
        self.txtNom_cli.setStatusTip(_translate("MainWindow", "Digite nome do cliente"))
        self.txtNom_cli.setPlaceholderText(_translate("MainWindow", "Nome cliente"))
        self.cbcSex_cli.setStatusTip(_translate("MainWindow", "Selecione sexo do cliente"))
        self.cbcSex_cli.setPlaceholderText(_translate("MainWindow", "Selecionar sexo"))
        self.cbcSex_cli.setItemText(0, _translate("MainWindow", "Indefinido"))
        self.cbcSex_cli.setItemText(1, _translate("MainWindow", "Femenino"))
        self.cbcSex_cli.setItemText(2, _translate("MainWindow", "Masculino"))
        self.txtCpf_cli.setStatusTip(_translate("MainWindow", "Digite CPF do cliente"))
        self.txtCpf_cli.setPlaceholderText(_translate("MainWindow", "CPF cliente"))
        self.txtId_cli.setStatusTip(_translate("MainWindow", "Código do cliente"))
        self.txtId_cli.setPlaceholderText(_translate("MainWindow", "Id"))
        self.txtEnd_cli.setStatusTip(_translate("MainWindow", "Endereço do cliente"))
        self.txtEnd_cli.setPlaceholderText(_translate("MainWindow", "Endereço cliente"))
        self.txtFon_cli.setStatusTip(_translate("MainWindow", "Telefone do cliente"))
        self.txtFon_cli.setPlaceholderText(_translate("MainWindow", "Fone cliente"))
        self.btnSal_cli.setStatusTip(_translate("MainWindow", "Cadastrar novo cliente"))
        self.btnSal_cli.setText(_translate("MainWindow", "Salvar"))
        self.btnAtu_cli.setStatusTip(_translate("MainWindow", "Atualizar dados do cliente"))
        self.btnAtu_cli.setText(_translate("MainWindow", "Atualizar"))
        self.btnExc_cli.setStatusTip(_translate("MainWindow", "Deletar cliente"))
        self.btnExc_cli.setText(_translate("MainWindow", "Excluir"))
        self.btnLim_cli.setStatusTip(_translate("MainWindow", "Limpar campos para poder cadastrar novo cliente"))
        self.btnLim_cli.setText(_translate("MainWindow", "Limpar"))
        self.txtPesNom_cli.setStatusTip(_translate("MainWindow", "Pesquisar clientes por nome"))
        self.txtPesNom_cli.setPlaceholderText(_translate("MainWindow", "Nome cliente"))
        self.btnPesNom_cli.setStatusTip(_translate("MainWindow", "Pesquisar clientes por nome"))
        self.btnPesNom_cli.setText(_translate("MainWindow", "Pesquisar"))
        self.table_cli.setStatusTip(_translate("MainWindow", "Selecione algum cliente para atualizar ou deletar"))
        item = self.table_cli.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Id"))
        item = self.table_cli.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Nome"))
        item = self.table_cli.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Sexo"))
        item = self.table_cli.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "CPF"))
        item = self.table_cli.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Endereço"))
        item = self.table_cli.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Fone"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabCli), _translate("MainWindow", "Clientes"))
        self.txtNom_ser.setStatusTip(_translate("MainWindow", "Digite nome do serviço"))
        self.txtNom_ser.setPlaceholderText(_translate("MainWindow", "Nome serviço"))
        self.cbbPro_ser.setStatusTip(_translate("MainWindow", "Selecione profissional que realizará este serviço"))
        self.cbbPro_ser.setPlaceholderText(_translate("MainWindow", "Selecionar profissional"))
        self.txtSer_ser.setStatusTip(_translate("MainWindow", "Digite valor do serviço"))
        self.txtSer_ser.setPlaceholderText(_translate("MainWindow", "Valor serviço"))
        self.txtId_ser.setStatusTip(_translate("MainWindow", "Código do serviço"))
        self.txtId_ser.setPlaceholderText(_translate("MainWindow", "Id"))
        self.horHor_ser.setStatusTip(_translate("MainWindow", "Digite duração aproximada do serviço"))
        self.pushButton_17.setStatusTip(_translate("MainWindow", "Cadastrar novo serviço"))
        self.pushButton_17.setText(_translate("MainWindow", "Salvar"))
        self.pushButton_18.setStatusTip(_translate("MainWindow", "Atualizar serviço"))
        self.pushButton_18.setText(_translate("MainWindow", "Atualizar"))
        self.pushButton_19.setStatusTip(_translate("MainWindow", "Deletar serviço"))
        self.pushButton_19.setText(_translate("MainWindow", "Excluir"))
        self.pushButton_21.setStatusTip(_translate("MainWindow", "Limpar campos para poder adicionar novo serviço"))
        self.pushButton_21.setText(_translate("MainWindow", "Limpar"))
        self.lineEdit_9.setStatusTip(_translate("MainWindow", "Pesquisar serviço por nome"))
        self.lineEdit_9.setPlaceholderText(_translate("MainWindow", "Nome serviço"))
        self.pushButton_15.setStatusTip(_translate("MainWindow", "Pesquisar serviço por nome"))
        self.pushButton_15.setText(_translate("MainWindow", "Pesquisar"))
        self.table_ser.setStatusTip(_translate("MainWindow", "Selecione algum serviço para atualizar ou deletar"))
        item = self.table_ser.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Id"))
        item = self.table_ser.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Nome"))
        item = self.table_ser.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Profissional"))
        item = self.table_ser.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Valor"))
        item = self.table_ser.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Duração"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSer), _translate("MainWindow", "Serviços"))
        self.menuAtendimentos.setTitle(_translate("MainWindow", "Atendimentos"))
        self.menuClientes.setTitle(_translate("MainWindow", "Usuários"))
        self.menuHor_rios.setTitle(_translate("MainWindow", "Relatórios"))
        self.menuServi_os.setTitle(_translate("MainWindow", "Opções"))
        self.menuSair.setTitle(_translate("MainWindow", "Sair"))
        self.actionClientes.setText(_translate("MainWindow", "Clientes"))
        self.actionClientes.setShortcut(_translate("MainWindow", "Alt+2"))
        self.actionHor_rios.setText(_translate("MainWindow", "Horários"))
        self.actionHor_rios.setShortcut(_translate("MainWindow", "Alt+1"))
        self.actionServi_os.setText(_translate("MainWindow", "Serviços"))
        self.actionServi_os.setShortcut(_translate("MainWindow", "Alt+3"))
        self.actionUsu_rios.setText(_translate("MainWindow", "Usuários"))
        self.actionUsu_rios.setShortcut(_translate("MainWindow", "Alt+4"))
        self.actionClientes_2.setText(_translate("MainWindow", "Clientes"))
        self.actionClientes_2.setShortcut(_translate("MainWindow", "Ctrl+2"))
        self.actionHor_rios_2.setText(_translate("MainWindow", "Horários"))
        self.actionHor_rios_2.setShortcut(_translate("MainWindow", "Ctrl+1"))
        self.actionServi_os_2.setText(_translate("MainWindow", "Serviços"))
        self.actionServi_os_2.setShortcut(_translate("MainWindow", "Ctrl+3"))
        self.actionAjuda.setText(_translate("MainWindow", "Ajuda"))
        self.actionAjuda.setShortcut(_translate("MainWindow", "Ctrl+A"))
        self.actionAddHor.setText(_translate("MainWindow", "Adicionar horários"))
        self.actionAddHor.setShortcut(_translate("MainWindow", "Ctrl+H"))
        self.actionSair_2.setText(_translate("MainWindow", "Sair"))
        self.actionSair_2.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionSobre.setText(_translate("MainWindow", "Sobre"))
        self.actionSobre.setShortcut(_translate("MainWindow", "Ctrl+I"))
import res_rc
