# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'trabalhoUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(370, 460)
        Form.setMinimumSize(QtCore.QSize(370, 460))
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 351, 151))
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 30, 331, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labhor = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.labhor.setObjectName("labhor")
        self.horizontalLayout.addWidget(self.labhor)
        self.timHor = QtWidgets.QTimeEdit(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.timHor.setFont(font)
        self.timHor.setObjectName("timHor")
        self.horizontalLayout.addWidget(self.timHor)
        self.btnLim_tim = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btnLim_tim.setStyleSheet("background-color: rgb(90, 90, 90);\n"
"color: rgb(255, 255, 255);")
        self.btnLim_tim.setObjectName("btnLim_tim")
        self.horizontalLayout.addWidget(self.btnLim_tim)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 90, 331, 51))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnAdd_hor = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.btnAdd_hor.setStyleSheet("background-color: rgb(0, 85, 0);\n"
"color: rgb(255, 255, 255);")
        self.btnAdd_hor.setObjectName("btnAdd_hor")
        self.horizontalLayout_2.addWidget(self.btnAdd_hor)
        self.btnDel_hor = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.btnDel_hor.setStyleSheet("background-color: rgb(170, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.btnDel_hor.setObjectName("btnDel_hor")
        self.horizontalLayout_2.addWidget(self.btnDel_hor)
        self.listTra = QtWidgets.QListWidget(Form)
        self.listTra.setGeometry(QtCore.QRect(10, 170, 351, 281))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.listTra.setFont(font)
        self.listTra.setObjectName("listTra")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Horários de Trabalho - Mehsys"))
        self.groupBox.setTitle(_translate("Form", "Editar Horários de Trabalho"))
        self.labhor.setText(_translate("Form", "Horário de Trabalho:"))
        self.btnLim_tim.setText(_translate("Form", "Limpar"))
        self.btnAdd_hor.setText(_translate("Form", "Adicionar"))
        self.btnDel_hor.setText(_translate("Form", "Deletar"))
